# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coveralls
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate json files
      run: |
        python generate_json.py
    - name: Test with pytest and generate coverage
      run: |
        coverage run --omit=tests/* -m pytest tests
        coverage report
    - name: Upload coverage data to coveralls.io
      run: |
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}